declare const SYMBOL_CACHED: unique symbol;
declare const SYMBOL_OBSERVABLE: unique symbol;
declare const SYMBOL_OBSERVABLE_BOOLEAN: unique symbol;
declare const SYMBOL_OBSERVABLE_FROZEN: unique symbol;
declare const SYMBOL_OBSERVABLE_READABLE: unique symbol;
declare const SYMBOL_OBSERVABLE_WRITABLE: unique symbol;
declare const SYMBOL_STORE: unique symbol;
declare const SYMBOL_STORE_KEYS: unique symbol;
declare const SYMBOL_STORE_OBSERVABLE: unique symbol;
declare const SYMBOL_STORE_TARGET: unique symbol;
declare const SYMBOL_STORE_VALUES: unique symbol;
declare const SYMBOL_STORE_UNTRACKED: unique symbol;
declare const SYMBOL_SUSPENSE: unique symbol;
declare const SYMBOL_UNCACHED: unique symbol;
declare const SYMBOL_UNTRACKED: unique symbol;
declare const SYMBOL_UNTRACKED_UNWRAPPED: unique symbol;
export { SYMBOL_CACHED, SYMBOL_OBSERVABLE, SYMBOL_OBSERVABLE_BOOLEAN, SYMBOL_OBSERVABLE_FROZEN, SYMBOL_OBSERVABLE_READABLE, SYMBOL_OBSERVABLE_WRITABLE, SYMBOL_STORE, SYMBOL_STORE_KEYS, SYMBOL_STORE_OBSERVABLE, SYMBOL_STORE_TARGET, SYMBOL_STORE_VALUES, SYMBOL_STORE_UNTRACKED, SYMBOL_SUSPENSE, SYMBOL_UNCACHED, SYMBOL_UNTRACKED, SYMBOL_UNTRACKED_UNWRAPPED };
